name: Unit test for bulk_pull_account.py script
on: push

jobs:
  build:
    name: bulk_pull_account_unit_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: python3 -m unittest bulk_pull_account.TestBulkPullAccount
